from enum import Enum


class Material(str, Enum):
    MINERAI_DE_FER = "minerai de fer"
    MINERAI_DE_CUIVRE = "minerai de cuivre"
    MINERAI_DE_CATERIUM = "minerai de caterium"
    QUARTZ_BRUT = "quartz brut"
    CRISTAL_DE_QUARTZ = "cristal de quartz"
    FILACTIF = "filactif"
    CONTROLEUR_IA = "controleur d'IA"
    SILICE = "silice"
    CHARBON = "charbon"
    LINGOT_ACIER = "lingot d'acier"
    LINGOT_CUIVRE = "lingot de cuivre"
    LINGOT_FER = "lingot de fer"
    LINGOT_CATERIUM = "lingot de caterium"
    POUTRE_ACIER = "poutre en acier"
    TUYAU_ACIER = "tuyau en acier"
    CALCAIRE = "calcaire"
    BETON = "beton"
    POUTRE_BETON_ARME = "poutre en beton armé"
    FIL_ELECTRIQUE = "fil electrique"
    STATOR = "stator"
    MOTEUR = "moteur"
    ROTOR = "rotor"
    EAU = "eau"
    PLAQUE = "plaque"
    PLAQUE_DE_FER_RENFORCEE = "plaque de fer renforcée"
    CADRE_MODULAIRE = "cadre modulaire"
    TIGE = "tige"
    VIS = "vis"
    CADRE_MODULAIRE_LOURD = "cadre modulaire lourd"
    CIRCUIT_IMPRIME = "circuit imprimé"
    TOLE_CUIVRE = "tole de cuivre"
    PETROLE_BRUT = "petrole brut"
    CAOUTCHOUC = "caoutchouc"
    RESIDUS_DE_PETROLE_LOURD = "residus de petrole lourd"
    PLASTIQUE = "plastique"
    COKE_DE_PETROLE = "coke de petrole"
    ORDINATEUR = "ordinateur"
    CABLE = "cable"
    CARBURANT = "carburant"
    BIDON_VIDE = "bidon vide"
    CARBURANT_CONDITIONNE = "carburant conditionné"
    CONNECTEUR_HAUTE_VITESSE = "connecteur haute vitesse"


class BuildingType(str, Enum):
    FOREUSE_MK1 = "Foreuse MK1"
    FOREUSE_MK2 = "Foreuse MK2"
    POMPE_EAU = "Pompe à eau"
    POMPE_A_PETROLE = "Pompe à petrole"
    FONDERIE_AVANCEE = "Fonderie avancée"
    CONSTRUCTEUR = "Constructeur"
    ASSEMBLEUSE = "Assembleuse"
    FONDERIE = "Fonderie"
    GENERATEUR_CHARBON = "Générateur à charbon"
    FACONNEUSE = "Faconneuse"
    RAFFINERIE = "Raffinerie"
    PACKAGEUR = "Packageur"
    GENERATEUR_CARBURANT = "Générateur à carburant"


class Recipe(str, Enum):
    LINGOT_ACIER = "lingot d'acier"
    POUTRE_ACIER = "poutre en acier"
    TUYAU_ACIER = "tuyau en acier"
    LINGOT_CATERIUM = "lingot de caterium"
    CONTROLEUR_IA = "controleur d'IA"
    CONNECTEUR_HAUTE_VITESSE = "connecteur haute vitesse"
    FILACTIF = "filactif"
    BETON = "beton"
    POUTRE_BETON_ARME = "poutre en beton armé"
    LINGOT_CUIVRE = "lingot de cuivre"
    LINGOT_FER = "lingot de fer"
    PLAQUE = "plaque"
    FIL_ELECTRIQUE = "fil electrique"
    STATOR = "stator"
    MOTEUR = "moteur"
    BRULE_CHARBON = "brule charbon"
    PLAQUE_DE_FER_RENFORCEE = "plaque de fer renforcée"
    CADRE_MODULAIRE = "cadre modulaire"
    TIGE = "tige"
    ROTOR = "rotor"
    VIS = "vis"
    CADRE_MODULAIRE_LOURD = "cadre modulaire lourd"
    CRISTAL_DE_QUARTZ = "cristal de quartz"
    SILICE = "silice"
    CIRCUIT_IMPRIME_EN_SILICIUM = "circuit imprimé en silicium"
    TOLE_CUIVRE = "tole de cuivre"
    CAOUTCHOUC = "caoutchouc"
    PLASTIQUE = "plastique"
    COKE_DE_PETROLE = "coke de petrole"
    BRULE_COKE_PETROLE = "brule coke petrole"
    ORDINATEUR = "ordinateur"
    CABLE = "cable"
    CARBURANT_RESIDUEL = "carburant résiduel"
    BIDON_VIDE = "bidon vide"
    CARBURANT_CONDITIONNE = "carburant conditionné"
    BRULE_CARBURANT = "brule carburant"


class MaterialType(int, Enum):
    PUR = 120
    NORMAL = 60
    IMPUR = 30
